version: 2.1

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo

########################
# yaml anchors (cache) #
########################
cache-restore-src: &cache-restore-src
  name: Restoring Cache (src)
  keys:
    - v1-src-{{ .Branch }}-{{ .Revision }}
    - v1-src-{{ .Branch }}-
    - v1-src-

cache-restore-deps: &cache-restore-deps
  name: Restoring Cache (deps)
  keys:
    - v1-deps-{{ checksum "build.sbt" }}
    - v1-deps-

cache-save-src: &cache-save-src
  name: Saving Cache (src)
  key: v1-src-{{ .Branch }}-{{ .Revision }}
  paths:
    - .git

cache-save-deps: &cache-save-deps
  name: Saving Cache (deps)
  key: v1-deps-{{ checksum "build.sbt" }}
  paths:
    - ~/.cache/coursier
    - ~/.ivy2/cache
    - ~/.sbt
    - ~/.m2

########
# jobs #
########
jobs:

  cache-warmup:
    executor: openjdk
    steps:
      - restore_cache: *cache-restore-src
      - checkout
      - restore_cache: *cache-restore-deps
      - run: sbt update
      - run: sbt test:update
      - save_cache: *cache-save-src
      - save_cache: *cache-save-deps

  sbt-test:
    executor: openjdk
    steps:
      - restore_cache: *cache-restore-src
      - checkout
      - restore_cache: *cache-restore-deps
      - run: sbt scalafmtSbtCheck
      - run: sbt scalafmtCheckAll

  sbt-publish:
    executor: openjdk
    steps:
      - restore_cache: *cache-restore-src
      - checkout
      - restore_cache: *cache-restore-deps
      - run: sbt publish

#########################
# yaml anchors (filter) #
#########################
filter-main: &filter-main
  branches:
    only: main

filter-release: &filter-release
  branches:
    ignore: /.*/
  tags:
    only: /^v\d+.\d+.\d+$/

#############
# workflows #
#############
workflows:
  version: 2

  main:
    jobs:
      - cache-warmup:
          filters: *filter-main
      - sbt-test:
          filters: *filter-main
          requires:
            - cache-warmup
      - sbt-publish:
          filters: *filter-main
          requires:
            - sbt-test

  release:
    jobs:
      - cache-warmup:
          filters: *filter-release
      - sbt-test:
          filters: *filter-release
          requires:
            - cache-warmup
      - sbt-publish:
          filters: *filter-release
          requires:
            - sbt-test
